# Generated by Django 4.1.5 on 2023-05-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='logo',
            field=models.FileField(blank=True, default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footer',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='thesis_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='cv',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='research',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='researchinterest',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.CharField(blank=True, default='#', max_length=250),
        ),
        migrations.AlterField(
            model_name='social',
            name='instagram',
            field=models.CharField(blank=True, default='#', max_length=250),
        ),
        migrations.AlterField(
            model_name='social',
            name='linkedin',
            field=models.CharField(blank=True, default='#', max_length=250),
        ),
        migrations.AlterField(
            model_name='social',
            name='mail',
            field=models.CharField(blank=True, default='#', max_length=250),
        ),
        migrations.AlterField(
            model_name='social',
            name='office',
            field=models.CharField(blank=True, default='#', max_length=250),
        ),
        migrations.AlterField(
            model_name='social',
            name='telegram',
            field=models.CharField(blank=True, default='#', max_length=250),
        ),
        migrations.AlterField(
            model_name='social',
            name='tiktok',
            field=models.CharField(blank=True, default='#', max_length=250),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter',
            field=models.CharField(blank=True, default='#', max_length=250),
        ),
        migrations.AlterField(
            model_name='social',
            name='youtube',
            field=models.CharField(blank=True, default='#', max_length=250),
        ),
    ]
