# Generated by Django 4.1.5 on 2023-05-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_experience_logo_alter_footer_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='types',
            field=models.CharField(choices=[('Journals', 'Journals'), ('Conferences', 'Conferences')], default='__________', max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='thesis_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
