# Generated by Django 4.1 on 2022-11-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_department_image_alter_post_imag_bottom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='responsble',
            new_name='responsible',
        ),
    ]
