# Generated by Django 4.1 on 2022-11-29 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_rename_responsble_department_responsible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='url',
            new_name='urls',
        ),
    ]
