# Generated by Django 4.1.5 on 2023-05-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_publication_types_alter_publication_thesis_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='logo',
            field=models.FileField(blank=True, default='default_user.png', upload_to=''),
        ),
    ]
