# Generated by Django 4.1.5 on 2023-05-02 10:07

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_experience_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfo',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
