# Generated by Django 4.1 on 2022-11-29 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_rename_url_department_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='urls',
        ),
    ]
