# Generated by Django 4.1.5 on 2023-06-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_homeinfo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('headline', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField(blank=True)),
                ('image', models.FileField(upload_to='')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('url', models.URLField()),
            ],
        ),
    ]
