# Generated by Django 4.1 on 2022-11-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imag_bottom',
            new_name='image_bottom',
        ),
    ]
