# Generated by Django 4.1.5 on 2023-06-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
