# Generated by Django 4.1.5 on 2023-06-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
