# Generated by Django 4.1 on 2022-11-30 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_rename_imag_bottom_post_image_bottom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_bottom',
            new_name='imag_bottom',
        ),
    ]
