# Generated by Django 4.1 on 2022-11-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_rename_image_bottom_post_imag_bottom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imag_bottom',
            new_name='image_bottom',
        ),
    ]
