# Generated by Django 4.1.5 on 2023-06-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_project_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='body',
            new_name='short',
        ),
    ]
