# Generated by Django 4.1.5 on 2023-06-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_rename_body_project_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
