# Generated by Django 4.1.5 on 2023-06-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_project_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short',
            field=models.TextField(),
        ),
    ]
