# Generated by Django 4.1.3 on 2022-12-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_contactus_aboutus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUs',
            new_name='About',
        ),
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
    ]
