# Generated by Django 4.1.3 on 2022-12-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_rename_aboutus_about_rename_contactus_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Call',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.CharField(max_length=200),
        ),
    ]
