# Generated by Django 4.1.5 on 2023-06-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_project_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
