# Generated by Django 4.1.3 on 2022-12-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_alter_contact_address_alter_contact_call_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Call',
            new_name='call',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
    ]
