# Generated by Django 4.1.5 on 2023-06-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_code',
            field=models.URLField(blank=True),
        ),
    ]
