# Generated by Django 4.1.3 on 2022-12-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_about_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='intro',
            field=models.CharField(max_length=200),
        ),
    ]
