# Generated by Django 4.1.5 on 2023-06-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_project_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='youtube',
            new_name='github',
        ),
    ]
