# Generated by Django 4.1.5 on 2023-06-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_rename_youtube_social_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
