# Generated by Django 4.1.5 on 2023-06-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_remove_research_link_publication_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='researchgate',
            field=models.CharField(blank=True, default='#', max_length=250),
        ),
    ]
