# Generated by Django 4.1.5 on 2023-06-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_social_researchgate'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfo',
            name='resume',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
