# Generated by Django 4.1.5 on 2023-06-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
