# Generated by Django 4.1.5 on 2023-09-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_hint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hint',
            name='priority',
        ),
        migrations.AlterField(
            model_name='hint',
            name='url',
            field=models.CharField(default='#', max_length=250),
        ),
    ]
