# Generated by Django 4.1.5 on 2023-09-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_remove_hint_priority_alter_hint_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='url',
            field=models.URLField(default='#', max_length=250),
        ),
    ]
