# Generated by Django 4.1.5 on 2023-09-16 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0024_experience_priority"),
        ("Main", "0028_alter_hint_url"),
    ]

    operations = []
