# Generated by Django 4.1.5 on 2023-10-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_merge_0024_experience_priority_0028_alter_hint_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='book',
            field=models.CharField(blank=True, default='#', max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
