# Generated by Django 4.2.11 on 2024-03-28 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0030_social_book_alter_project_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('priority', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.cat_projects'),
        ),
    ]
