# Generated by Django 4.2.11 on 2024-03-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0031_cat_projects_project_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_projects',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
