# Generated by Django 4.2.11 on 2024-03-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_cat_projects_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_projects',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
